#!/usr/bin/env bash
set -eo pipefail

PATH="${PATH-}"
PYTHONPATH="${PYTHONPATH-}"
AMENT_PREFIX_PATH="${AMENT_PREFIX_PATH-}"
LD_LIBRARY_PATH="${LD_LIBRARY_PATH-}"
if [ -z "${RMW_IMPLEMENTATION-}" ]; then
  RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
fi
export RMW_IMPLEMENTATION

set -u
shopt -s nullglob

polyflow_prepend_path_list() {
  local var_name="$1"
  local prefix_list="$2"
  local current_value="${!var_name}"

  local IFS=':'
  read -ra parts <<< "$prefix_list"
  for (( idx=${#parts[@]}-1; idx>=0; idx-- )); do
    local part="${parts[idx]}"
    [ -z "$part" ] && continue
    case ":${current_value}:" in
      *":${part}:"*) ;;
      *) current_value="${part}${current_value:+:}${current_value}" ;;
    esac
  done

  printf -v "$var_name" '%s' "$current_value"
}

PYTHONPATH_BASE="@pythonPath@"
AMENT_PREFIX_BASE="@amentPrefixPath@"
LIBRARY_PATH_BASE="@workspaceLibraryPath@"

polyflow_prepend_path_list AMENT_PREFIX_PATH "$AMENT_PREFIX_BASE"
export AMENT_PREFIX_PATH

polyflow_prepend_path_list LD_LIBRARY_PATH "$LIBRARY_PATH_BASE"
export LD_LIBRARY_PATH

set +u
for prefix in @workspaceRuntimePrefixes@; do
  for script in "$prefix"/setup.bash "$prefix"/local_setup.bash \
                "$prefix"/install/setup.bash "$prefix"/install/local_setup.bash \
                "$prefix"/share/*/local_setup.bash "$prefix"/share/*/setup.bash; do
    if [ -f "$script" ]; then
      echo "[INFO] Sourcing $script" >&2
      . "$script"
    fi
  done
done
set -u

polyflow_prepend_path_list PYTHONPATH "$PYTHONPATH_BASE"
export PYTHONPATH

echo "[DEBUG] AMENT_PREFIX_PATH=$AMENT_PREFIX_PATH" >&2
echo "[DEBUG] PYTHONPATH=$PYTHONPATH" >&2
echo "[DEBUG] RMW_IMPLEMENTATION=$RMW_IMPLEMENTATION" >&2

# Launch the pre-generated workspace launch file from the built workspace
# This file is generated by polyflow-studio and copied during the Nix build
WORKSPACE_LAUNCH="@rosWorkspace@/share/nodes.launch.py"

if [ ! -f "$WORKSPACE_LAUNCH" ]; then
  echo "[ERROR] Workspace launch file not found: $WORKSPACE_LAUNCH" >&2
  echo "[ERROR] This file should be generated by polyflow-studio and included in the build" >&2
  exit 1
fi

echo "[INFO] Launching workspace from $WORKSPACE_LAUNCH" >&2
exec ros2 launch "$WORKSPACE_LAUNCH"
